"""OWASP ZAP wrapper for dynamic web application / API security testing."""

import logging
import os
import shutil
import socket
import tempfile
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from core.project_paths import ProjectPaths
from domain.tools.interface import ExecutionContext, ExecutionPass
from infrastructure.tools.parsers.zap import (
    parse_zap_json,
    parse_zap_json_string,
    parse_zap_xml,
)
from infrastructure.tools.wrappers.base.zap import BaseZapTool

logger = logging.getLogger(__name__)


class ZAPLocalTool(BaseZapTool):
    """Wrapper for OWASP ZAP DAST scanning.

    Supports two invocation modes:

    **Quick-scan (default):**
        ``zap.sh -cmd -quickurl <url> -quickprogress -quickout <file>``

    **OpenAPI mode:**
        ``zap.sh -cmd -openapifile <oas3_path> -openapitargeturl <url>``
        ``        -quickprogress -quickout <file>``

    OpenAPI mode is activated automatically by ``build_execution_passes``
    when an OAS3 file is available.  Resolution order:

    1. ``repo.oas3_path`` — user-supplied endpoint file
    2. ``repo.merged_oas3_path`` — generated by the URL discovery pipeline
    3. Fall back to ``-quickurl`` mode (no ``openapi_file``)

    The ``openapi_file`` kwarg passed to ``build_command`` overrides this
    resolution when called directly.
    """

    def __init__(self, config=None) -> None:
        # Path to zap.sh from commands.json; falls back to bare "zap.sh" on PATH
        self._zap_path: str = config.path if config is not None else "zap.sh"
        # Set by build_command(); read by parse_output()
        self._last_report_path: Path | None = None

    @property
    def command(self) -> str:
        return "zap.sh"

    def check_available(self) -> bool:
        """Return True if the configured zap.sh path exists."""
        return shutil.which("zap.sh") is not None

    def get_version(self) -> str | None:
        # calling zap.sh with the --version argument
        # takes a long time and delays boot
        # todo: Find more performant way to get version at boot
        return shutil.which(self._zap_path)

    def build_command(self, **kwargs) -> list[str]:
        """Build the ZAP scan argv list.

        Keyword Args:
            base_url (str): API base URL to scan. Required.
            endpoints (Dict[str, List[str]]): Endpoint map from the project's
                endpoint config.  Informational only in quick-scan mode.
            api_type (str): ``"rest"`` or ``"graphql"`` (default: ``"rest"``).
            auth_token (Optional[str]): Bearer token for authenticated targets.
            output_file (Optional[str]): Filesystem path for the ZAP JSON report.
            openapi_file (Optional[str]): Path to an OAS3 file produced by Noir.
                When provided, ZAP imports the spec via ``-openapifile`` and
                ``-openapitargeturl`` instead of using ``-quickurl`` mode.
        """
        base_url: str | None = kwargs.get("base_url")
        if not base_url:
            raise ValueError("base_url is required for ZAP")

        output_file: str | None = kwargs.get("output_file")
        if not output_file:
            output_file = str(
                Path(tempfile.gettempdir()) / f"zap_report_{os.getpid()}.json"
            )

        # zap.sh cd's to its install dir before launching Java, so any relative
        # path would be resolved there.  Always pass an absolute path.
        output_file = str(Path(output_file).resolve())
        self._last_report_path = Path(output_file)

        openapi_file: str | None = kwargs.get("openapi_file")

        # zap.sh cd's to its install dir before launching Java, so any relative
        # path for openapi_file would be resolved there.  Always use absolute.
        if openapi_file:
            openapi_file = str(Path(openapi_file).resolve())

        # ZAP defaults its HTTP proxy to port 8080, which may already be in use
        # (e.g. by the tally web server or a scanned app).  Use a fresh isolated
        # home directory (-dir) per scan so ZAP writes its own config.xml with
        # the chosen port — this avoids TOCTOU races and any residual config from
        # a previous run overriding our -port flag.
        zap_home = str(Path(tempfile.gettempdir()) / f"zap_home_{os.getpid()}")
        proxy_port = str(_find_free_port())

        if openapi_file:
            # OpenAPI mode: ZAP imports the OAS3 spec so it discovers all defined
            # paths, then uses -quickurl to trigger the spider + active scan.
            # Without -quickurl the scan does not execute and no report is written.
            return [
                self._zap_path,
                "-cmd",
                "-dir",
                zap_home,
                "-port",
                proxy_port,
                "-openapifile",
                openapi_file,
                "-openapitargeturl",
                base_url,
                "-quickurl",
                base_url,
                "-quickprogress",
                "-quickout",
                output_file,
            ]

        # Quick-scan mode: ZAP crawls the target URL directly.
        return [
            self._zap_path,
            "-cmd",
            "-dir",
            zap_home,
            "-port",
            proxy_port,
            "-quickurl",
            base_url,
            "-quickprogress",
            "-quickout",
            output_file,
        ]

    def parse_output(self, output: str, files: dict[str, Path]) -> dict[str, Any]:
        """Parse ZAP scan output into structured data."""
        # 1. Report file written by ZAP itself
        if self._last_report_path is not None and self._last_report_path.exists():
            suffix = self._last_report_path.suffix.lower()
            if suffix == ".xml":
                return parse_zap_xml(self._last_report_path)
            return parse_zap_json(self._last_report_path)

        # 2. Stdout file saved by executor (may contain progress text, not JSON)
        stdout_path = files.get("stdout")
        if stdout_path is not None and stdout_path.exists():
            return parse_zap_json(stdout_path)

        # 3. Raw output string (fallback — unlikely to be valid JSON)
        return parse_zap_json_string(output)

    def build_execution_passes(self, context: ExecutionContext) -> list[ExecutionPass]:
        """Return one ExecutionPass for ZAP.

        When an OAS3 file is available for the target repository, it is passed
        as ``openapi_file`` so that ZAP uses OpenAPI mode.  Resolution order:

        1. ``repo.oas3_path`` — user-supplied endpoint file
        2. ``repo.merged_oas3_path`` — generated by the URL discovery pipeline
        3. Fall back to ``-quickurl`` mode (no ``openapi_file``)
        """
        assert context.repo is not None
        repo = context.repo

        output_dir = ProjectPaths.from_canonical(
            context.base_path, context.project_name
        ).tool_output_dir("zap")
        output_dir.mkdir(parents=True, exist_ok=True)
        ts = datetime.now(UTC).strftime("%Y%m%dT%H%M%S")
        output_file = str(output_dir / f"{repo.name}_{ts}_report.json")

        kwargs: dict[str, Any] = {
            "base_url": repo.base_urls[0],
            "output_file": output_file,
        }

        openapi_file: str | None = repo.oas3_path or repo.merged_oas3_path or None
        if openapi_file:
            kwargs["openapi_file"] = openapi_file
        else:
            logger.info(
                "ZAP: no OAS3 file for %s — using quick-scan mode. "
                "Run Katana, Noir, or configure an endpoint file to "
                "enable OpenAPI mode.",
                repo.name,
            )

        return [
            ExecutionPass(
                label_suffix=repo.name,
                kwargs=kwargs,
            )
        ]


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _find_free_port() -> int:
    """Ask the OS to assign a free TCP port and return it.

    Uses ``socket.bind(("", 0))`` so the OS picks an available port.  There is
    a small TOCTOU window between this call and ZAP starting, but in practice
    scans run sequentially and the race is negligible.
    """
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("", 0))
        return s.getsockname()[1]
