"""Filesystem port for draft markdown files."""

from __future__ import annotations

from typing import Protocol


class DraftFilesPort(Protocol):
    def read(self, section: str) -> str | None: ...
    def write(self, section: str, content: str) -> None: ...
    def exists(self, section: str) -> bool: ...
    def delete(self, section: str) -> None: ...
    def ensure_dir(self) -> None: ...
