"""Persistence port for the global ``projects`` registry table."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from domain.projects.entry import ProjectRow


class ProjectRegistryRepositoryPort(Protocol):
    def ping(self) -> None: ...
    def init_schema(self) -> None: ...
    def list_active(self) -> list[ProjectRow]: ...
    def list_all(self) -> list[ProjectRow]: ...
    def get_by_id(self, project_id: int) -> ProjectRow | None: ...
    def get_by_name(self, name: str) -> ProjectRow | None: ...
    def insert(self, name: str, path: str) -> int: ...
    def archive(self, name: str) -> None: ...
    def unarchive(self, name: str, new_path: str) -> None: ...
    def rename(self, old: str, new: str, new_path: str) -> None: ...
    def sync_from_filesystem(self, base_path: str) -> None: ...
