"""Persistence port for the global ``projects`` registry table.

Concrete implementation lives at
``infrastructure.store.project_registry.ProjectRegistryRepository``.
The registry holds one row per known project (id, name, on-disk path,
creation timestamp, optional archive timestamp) in ``tally.db``.

Read methods return ``dict | None`` / ``list[dict]`` as a transitional
shape; field names match the row columns exactly. Promotion to a
``ProjectRow`` dataclass is deferred to an A5e-followup slice that
migrates the REPL command modules and web routes from dict
subscripting to attribute access.
"""

from __future__ import annotations

from typing import Protocol


class ProjectRegistryRepositoryPort(Protocol):
    def ping(self) -> None: ...
    def init_schema(self) -> None: ...
    def list_active(self) -> list[dict]: ...
    def list_all(self) -> list[dict]: ...
    def get_by_id(self, project_id: int) -> dict | None: ...
    def get_by_name(self, name: str) -> dict | None: ...
    def insert(self, name: str, path: str) -> int: ...
    def archive(self, name: str) -> None: ...
    def unarchive(self, name: str, new_path: str) -> None: ...
    def rename(self, old: str, new: str, new_path: str) -> None: ...
    def sync_from_filesystem(self, base_path: str) -> None: ...
