"""Persistence port for the per-project repositories table."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from core.config.schemas.repository import Repository


class ProjectRepoRepositoryPort(Protocol):
    def list_active(self) -> list[Repository]: ...
    def list_all(self) -> list[Repository]: ...
    def get_by_id(self, repo_id: int) -> Repository | None: ...
    def get_active_by_id(self, repo_id: int) -> Repository | None: ...
    def get_by_name(self, name: str) -> Repository | None: ...
    def find_id_by_name(self, name: str) -> int | None: ...
    def is_deleted(self, repo_id: int) -> bool: ...
    def insert(self, repo: Repository) -> int: ...
    def update(self, repo_id: int, repo: Repository) -> None: ...
    def rename(self, repo_id: int, new_name: str) -> None: ...
    def set_url_seed_file(self, repo_id: int, path: str | None) -> None: ...
    def soft_delete(self, repo_id: int, when: str | None = None) -> None: ...
    def restore(self, repo_id: int) -> None: ...
