"""Persistence port for the ``triage_batches`` table."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from domain.triage.entry import TriageBatchRow, TriageRunSummary


class TriageBatchRepositoryPort(Protocol):
    def create_batches(
        self, run_id: int, tool: str, repo: str, segment: str
    ) -> int: ...
    def claim_batch(self, run_id: int) -> TriageBatchRow | None: ...
    def complete_batch(self, batch_id: int, status: str) -> None: ...
    def reset_stale_batches(self, run_id: int) -> int: ...
    def reset_for_resume(self, run_id: int) -> int: ...
    def get_active_finding_combos(
        self, skip_tools: frozenset[str]
    ) -> list[tuple[str, str, str]]: ...
    def cancel_remaining(self, run_id: int) -> int: ...
    def list_run_ids_for_project(
        self, *, offset: int = 0, limit: int = 20
    ) -> tuple[list[int], int]: ...
    def list_for_run(self, run_id: int) -> list[TriageBatchRow]: ...
    def summarize_for_run(self, run_id: int) -> TriageRunSummary | None: ...
